#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2009 Jakub Wilk <jwilk@jwilk.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

import argparse
import sys

import leechy

leechy.register_all_plugins()

argparser = argparse.ArgumentParser()
argparser.add_argument('--debug', '-D', action='store_true')
argparser.add_argument('urls', metavar='<url>', nargs='+', help='URL to download')
options = argparser.parse_args(sys.argv[1:])

for uri in options.urls:
    leechy.log_info('>>> %s' % uri)
    try:
        leechy.dispatch(uri, debug=options.debug)
    except leechy.NoMatchingPlugin:
        leechy.log_error('Plugin not found.')
    except leechy.FileNotFound:
        leechy.log_error('File not found.')
    except leechy.SimultaneousDownload:
        leechy.log_error('Too many simultaneous downloads. Please try again later.')
    except leechy.TemporaryFailure:
        leechy.log_error('Temporary server failure. Please try again later.')
    except leechy.WgetFailure:
        leechy.log_error('Download failed. Maybe try again later?')
    except leechy.ApiError, ex:
        msg = 'API error (code=%s)' % (ex.code,)
        if (ex.dump_name != None):
            msg += ' Last page dumped into: %s' % (ex.dump_name,)
        leechy.log_error(msg)
        del msg
        sys.exit(1)
    except KeyboardInterrupt:
        leechy.log_error('Interrupted by user.')
        sys.exit(2)
    leechy.log_info('')

# vim:ts=4 sw=4 et
